### ISSUE TITLE
Dataset thesis

### ISSUE THREAD

**Issue by LisanneLageweg** [mshafieek/ADS-Missing-data-social-network#14]
Since we are using the "part of apollo data", I assume this is a subsample of the original data? Is there additional information about this? For the data part of the thesis.

**Comment by mshafieek** [comment]
@LisanneLageweg. Yes, it is a subset of that. For more details, you can refer to the changepoint paper I shared with you earlier. It would be helpful if you could provide a summary of the data section from that paper, and if you wish, you can also explore additional information by conducting a quick search online. Feel free to reach out if you have any further inquiries.
