### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by JesseJvdw** [mshafieek/ADS-Missing-data-social-network#16]
I found out that somewhere in my code something went wrong and I got the wrong estimates in both the true rem and the imputed list. Now I try to rerun my code but now I am running out of memory.  My memory is able to run 74 simulations. Do you reckon that is enough or should I run 74 simulations a few time?

also getting a warning now: Warning: stack imbalance in 'cbind', 92 then 91

**Comment by JesseJvdw** [comment]
Just found out running it a few times also causes memory issues.

**Comment by gerkovink** [comment]
Try to save only the pooled model output. Have a look at the code that I provided for Vira (see the Gerko folder) and use a modular design that you can later stitch together. That helps with memory

**Comment by gerkovink** [comment]
What error do you receive exactly?

**Comment by JesseJvdw** [comment]
! 'Calloc' could not allocate memory (931680 of 16 bytes)

**Comment by gerkovink** [comment]
Insufficient ram. Either increase the memory limit, if still possible, or run a modular one. If you send or prepera for me a working RStudio project, I can try to run it for you tomorrow.

**Comment by JesseJvdw** [comment]
I'm trying to run a 1000 simulations but I'll check if I can do 100 with 10 at the time.

**Comment by JesseJvdw** [comment]
Managed to run a 100
