### ISSUE TITLE
Missing data 

### ISSUE THREAD

**Issue by LisanneLageweg** [mshafieek/ADS-Missing-data-social-network#2]
Hello,

I have now made a part of the data missing using MCAR and MAR. But now I wonder, since I have the topic sender, is it intended that only the sender column has missing values? Or should all columns have missing values?

**Comment by gerkovink** [comment]
Only the sender should have missing data.

**Comment by gerkovink** [comment]
Also, don't forget to check the generated missingness with `mice::md.pattern()` or `ggmice::plot_pattern()`

**Comment by gerkovink** [comment]
See also #4 for an illustration of the missing data pattern with `mice::md.pattern()` after `mice::ampute()`

**Comment by gerkovink** [comment]
Closing as this is solved
