### ISSUE TITLE
error remstats

### ISSUE THREAD

**Issue by LisanneLageweg** [mshafieek/ADS-Missing-data-social-network#3]
When I try to use the remstats() function, I encounter an error. How can I resolve this?

> statObject <- remstats(edgelist = PartOfApollo_13, tie_effects = effects)
Error: 'reh' is not an exported object from 'namespace:remify'

**Comment by gerkovink** [comment]
@mshafieek Can you answer this?

**Comment by mshafieek** [comment]
Sure, I also replied to Jesse's email regarding this matter. The package is being updated at Tilburg University and I have already contacted the relevant person to report the problem. I'll let you all know as soon as I get a response.

**Comment by gerkovink** [comment]
Closing as this issue is solved. See e.g. gerkovink/mice#8 or #4  for details on how to use `devtools::install_github()`. In this case:

```r 
devtools::install_github("TilburgNetworkGroup/remstats@v.3.1.0")
```
