### ISSUE TITLE
REM 

### ISSUE THREAD

**Issue by LisanneLageweg** [mshafieek/ADS-Missing-data-social-network#5]
> fit <- remstimate::remstimate(reh = reh, stats = out, estimator = "MLE", timing = "interval")
Error in if (!(method %in% c("MLE", "GDADAMAX", "BSIR", "HMC"))) { : 
  the condition has length > 1
  
  
  when I want to fit the model, I keep getting this error. I don't know how to solve this. 

@mshafieek

**Comment by mshafieek** [comment]
Probably they changed or reduced the arguments. Can you issue this in the corresponding repository of TilburgNetworkGroup under remstimate. @LisanneLageweg

**Comment by gerkovink** [comment]
Solved in TilburgNetworkGroup/remstimate#23
