### ISSUE TITLE
remstats - cox data

### ISSUE THREAD

**Issue by mshafieek** [mshafieek/ADS-Missing-data-social-network#6]
@vira-dvoriak I already check the remstats explanation and there they mentioned the following

<img width="1096" alt="Screenshot 2023-05-17 at 16 47 11" src="https://github.com/mshafieek/ADS-Missing-data-social-network/assets/63051665/1e50756f-4284-4a9e-82f1-f54d21755f55">

....
The remstats() function outputs a 3-dimensional array with statistics. On the rows of this array are the time points, the columns refer to the potential events in the riskset and the slices refer to the different statistics:

dim(out)

this is exactly what we need for the Cox model, coxph(),  but there we need to convert it to a data frame. I try to find you an example soon. But before that, you could try it yourself.

**Comment by vira-dvoriak** [comment]
Thank you, I will try it.

**Comment by vira-dvoriak** [comment]
Do we need then 3 separate data frames 3882x240 for each statistic for the crox model?

**Comment by mshafieek** [comment]
@vira-dvoriak, no at all. You should create a data frame including the values of all statistics. Let's say one data frame with 5 columns: one for time, one for status (**_0_** (non occurred events ) and **_1_** (occurred events) in risk set), and three columns for three statistics.

**Comment by mshafieek** [comment]
@vira-dvoriak, this is an example of the code:

library(survival)
cox_t <- coxph(Surv(time, status) ~ x1 + x2 + x3, data=coxdata)

where xi, i=1,2,3  is the statistics of interest such as inertia,  coxdata is the data frame that we already talked about that which includes all the statistics +time+status, please note that in this data we have the full risk set in each time point. This data can be extracted from the output of remstats. Please read the explanation of remstats precisely. 

Hope this helps. Please let me know if you have any questions.

**Comment by mshafieek** [comment]
Let say we have the following edgelist:

a-->b   t=0.5  day
c-->a.  t= 0.6 day
a-->c   t= 0.67 day

the data frame is as follows:
**s**     **r**.       **t**
a            b              0.5
c            a.             0.6
a            c              0.67

now the cox data should be something as follow:
**s**     **r**.       **t**               status
**a              b             0.5                    1**
a.             c             0.5                    0
b.             a             0.5                    0
b.             c             0.5                    0
c.             a             0.5                    0
c.             b             0.5                    0

a              b             0.6                    0
a.             c             0.6                    0
b.             a             0.6                    0
b.             c             0.6                    0
**c.             a             0.6                    1**
c.             b             0.6                    0

a              b             0.67                0
**_a.             c             0.67                1_**
b.             a             0.67                0
b.             c             0.67                0
c.             a             0.67                0
c.             b            0.67                 0

This is the cox data.
