### ISSUE TITLE
Error in is_igraph(graph) : argument "graph" is missing, with no default

### ISSUE THREAD

**Issue by LisanneLageweg** [mshafieek/ADS-Missing-data-social-network#7]
apollo.renamed <- PartOfApollo_13
apollo.renamed <- apollo.renamed %>%

rename(
actor1 = sender,
actor2 = receiver
)
Define effects
effects <- ~reciprocity() + indegreeSender() + outdegreeReceiver()

Prepare event history
reh <- remify::remify(edgelist = apollo.renamed, model = "tie")

Compute statistics
statsObject <- remstats(reh = reh, tie_effects = effects)
Error in is_igraph(graph) : argument "graph" is missing, with no default

I posted this issue a few days ago in the github from remstats but they haven't answered yet. But do you know how I can fix this error?

**Comment by mshafieek** [comment]
@LisanneLageweg, I think it is again package-based error. Please see whether in the new version of remstats they used graph as an argument. I will also check it myself.
