### ISSUE TITLE
error in REM

### ISSUE THREAD

**Issue by LisanneLageweg** [mshafieek/ADS-Missing-data-social-network#8]
when I use the excact same code as Vira does. I keep getting errors. First the error in the other issue. Now I receive this error. I tried everyting, redownloading R, checking the packages, redownloading the packages, restarting R, etc. I really don't know how I can fix this ..  

apollo.renamed <- PartOfApollo_13
apollo.renamed <- apollo.renamed %>% 
  rename(
    actor1 = sender,
    actor2 = receiver
  )

# Define effects
effects <- ~ -1 + reciprocity() + indegreeSender() + outdegreeReceiver()

# Prepare event history
reh <- remify(edgelist = apollo.renamed, model = "tie")

# Compute statistics
statsObject <- remstats::remstats(tie_effects = effects, reh = reh)
Error in reciprocity() : argument "graph" is missing, with no default

**Comment by mshafieek** [comment]
@LisanneLageweg , did you ask it from TilburgNetwork Group?

**Comment by LisanneLageweg** [comment]
@mshafieek yes, 5 days ago. Still no response.

**Comment by mshafieek** [comment]
@LisanneLageweg, ask this under the corresponding package. that is under remify.

**Comment by LisanneLageweg** [comment]
[TilburgNetworkGroup](https://github.com/TilburgNetworkGroup)
/
[remstats](https://github.com/TilburgNetworkGroup/remstats)

this is where I posted the issue, is that not correct?

**Comment by LisanneLageweg** [comment]
@mshafieek

**Comment by mshafieek** [comment]
@LisanneLageweg, So, post under remify.
